version: '3.8'
services:
  best-shopping-api:
    container_name: best-shopping-api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
      - 5555:5555
    depends_on:
      - best-shopping-db
    volumes:
      - .:/usr/src/app
    command: npm run dev-container

  best-shopping-db:
    container_name: best-shopping-db
    image: postgres
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB_HOST=${DB_HOST}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  data: {}
